### ISSUE TITLE
remove stamen basemap

### ISSUE THREAD

**Issue by vincentsarago** [developmentseed/tipg#104]
https://github.com/developmentseed/tipg/blob/10d2a56bf6b56d1623dc1ae6f22ceaa95eb59b7d/tipg/templates/map.html#L32-L62

https://stamen.com/here-comes-the-future-of-stamen-maps/

**Comment by krishnaglodha** [comment]
I can work on it

**Comment by krishnaglodha** [comment]
@vincentsarago  should we use something like maplibre? 
or something simple as
```
L.tileLayer('https://tile.openstreetmap.org/{z}/{x}/{y}.png', {
    maxZoom: 19,
    attribution: '© [OpenStreetMap](http://www.openstreetmap.org/copyright)'
}).addTo(map);
```

**Comment by vincentsarago** [comment]
Yes 🙏

**Comment by krishnaglodha** [comment]
Ok, will add ‘OSM’

**Comment by krishnaglodha** [comment]
How can I test this ?

**Comment by vincentsarago** [comment]
no need to really test it other than checking locally if it works

**Comment by vincentsarago** [comment]
done in https://github.com/developmentseed/tipg/commit/8ee337e7dd81397d3ac3959984948541631c652b
