### ISSUE TITLE
Add or Clarify Support For Function Overloading

### ISSUE THREAD

**Issue by aemonm** [developmentseed/tipg#106]
Currently, it does not look like [function overloading](https://www.postgresql.org/docs/current/xfunc-overload.html) [is supported](https://github.com/developmentseed/tipg/blob/main/tipg/dependencies.py#L53-L54). If there are no plans to somehow support overloading soon, it would be nice if this were mentioned in the docs.

**Comment by vincentsarago** [comment]
done in https://github.com/developmentseed/tipg/pull/107 🙏 

as of now we need a `unique` id for the functions when we register them in the catalog so we can use them as `collections` (e.g Table or Function). Overloading (so finding the function based on the attribute) might be really hard to achieve so for now the update to the docs is 💯 

Thanks
