### ISSUE TITLE
ROOT_PATH in environment docker

### ISSUE THREAD

**Issue by grigoroffbenj** [developmentseed/tipg#183]
Hi, 
thanks for your work !!!! 
it's will be so cool if you can set ROOT_PATH in environment variable in docker and in tipg.settings.APISettings class link! 
Eg:  [Here docs](https://developmentseed.org/tipg/user_guide/configuration/#tipg-application-settings)
it's permit to use as it the docker images instead to rebuild it. To use in docker compose stack and traefik path rewrite.

**Comment by vincentsarago** [comment]
have you tried setting `TIPG_ROOT_PATH` ?

**Comment by vincentsarago** [comment]
updated the docs https://github.com/developmentseed/tipg/commit/f893091e6178e1cab449007dbab46dfea6f2be88
