### ISSUE TITLE
remove vector tiles viz in `/collection` pages and add a `/collections/{collection}/map` viewer 

### ISSUE THREAD

**Issue by vincentsarago** [developmentseed/tipg#26]
https://github.com/developmentseed/tipg/blob/4923d32abe434ddd549f41456c08b91d75762b65/tipg/templates/collection.html#L61-L91

When working with big collection, the viewer is not really useful, and removing this will also help splitting the features api and the tiles api.

cc @bitner

**Comment by bitner** [comment]
:thinking: so... the biggest use case I had for having the vector tiles in the collection was just so I had an easy place that I could quickly just see that vector tiles were working. I definitely see your point though.

**Comment by vincentsarago** [comment]
done in https://github.com/developmentseed/tipg/pull/28
