### ISSUE TITLE
Connect to alternative schemas

### ISSUE THREAD

**Issue by KoalaGeo** [developmentseed/tipg#44]
Hi, 

I'm running postgres, and have all my geospatial data in a schema "published" rather than using public. 

I'm struggling to connect to that schema - tipg is only connecting to public.

In the Dockerfile I've tried 

ENV POSTGRES_DBNAME=oraetl?options=-c%20search_path=published
and
ENV TIPG_DB_SCHEMAS=["published"]

Neither have worked. Any suggestions?

**Comment by vincentsarago** [comment]
🤔 

I have a PgSTAC database that I start with docker compose (https://github.com/developmentseed/eoAPI/blob/master/docker-compose.yml#L129-L143) and then pass `pgstac` for the schemas and it work well 🤷 

```
DATABASE_URL=postgresql://username:password@0.0.0.0:5439/postgis TIPG_DB_SCHEMAS='["pgstac"]' TIPG_DB_FUNCTIONS='[]' TIPG_TABLE_CONFIG__pgstac_items__pk=id uvicorn tipg.main:app --port 8000 --reload
```

<img width="1594" alt="Screenshot 2023-03-22 at 12 02 15 PM" src="https://user-images.githubusercontent.com/10407788/226884216-e44d253e-7bc8-4bb9-9361-c0d8aa827fce.png">

**Comment by KoalaGeo** [comment]
Tried:
```
ENV DATABASE_URL=postgresql://user:password@192.171.148.87/oraetl
ENV TIPG_DB_SCHEMAS='["published"]'
```
But weirdly it's still just picking up 3 of the postgis functions: 
![image](https://user-images.githubusercontent.com/33657876/226900853-5293ffa7-b32c-4779-9ba2-189e531e1c6a.png)

**Comment by vincentsarago** [comment]
ok I can reproduce this. It's weird that I had no issues using pgstac schema 

```
# Launch database
docker-compose up database -d 

# Create a copy of `public.countries` in `myschema.countries`
psql postgresql://username:password@0.0.0.0:5439/postgis -c "CREATE SCHEMA IF NOT EXISTS myschema; SET schema 'myschema'; DROP TABLE IF EXISTS myschema.countries CASCADE; CREATE TABLE myschema.countries AS SELECT * FROM public.countries; SELECT count(*) FROM myschema.countries;"

# Start TiPG service
DATABASE_URL=postgresql://username:password@0.0.0.0:5439/postgis TIPG_DB_SCHEMAS='["myschema"]' TIPG_DB_FUNCTIONS='[]' uvicorn tipg.main:app --port 8000 --reload
```

```
curl http://127.0.0.1:8000/collections | jq
{
  "links": [
    {
      "href": "http://127.0.0.1:8000/collections",
      "rel": "self",
      "type": "application/json"
    }
  ],
  "numberMatched": 0,
  "numberReturned": 0,
  "collections": []
}
```

**Comment by KoalaGeo** [comment]
Pleased it's not just me! 

Not an immediate fix but what about functionality matching pg_featureserv - where you don't have to specify the schema, the application finds everything which the $user has SELECT permissions for? 

Then all the access control is at the DB side.

**Comment by KoalaGeo** [comment]
Don't know if it's helpful or not but we recently added CQL functionality to the PostGres provider in pygeoapi with sqlalchemy & pygeofilter 
if there's anything you could reuse -  https://github.com/geopython/pygeoapi/pull/964

**Comment by KoalaGeo** [comment]
@bitner any ideas?

**Comment by vincentsarago** [comment]
I'm also able to connect to other schema when I add them in 
https://github.com/developmentseed/tipg/blob/99c7de7ff538a1a077c7fc02bca30b29be544df4/tipg/db.py#L45

eg 
```
    await conn.execute(
        """
            SELECT set_config(
                'search_path',
                'pg_temp,myschema,public,' || current_setting('search_path', false),
                false
                );
            """
    )
```

**Comment by KoalaGeo** [comment]
If you did similar to [L216](https://github.com/developmentseed/tipg/blob/99c7de7ff538a1a077c7fc02bca30b29be544df4/tipg/sql/dbcatalog.sql#L216) but used `has_schema_privilege` then wouldn't need to define the schema in the config (think thats what https://github.com/CrunchyData/pg_featureserv/blob/master/internal/data/db_sql.go#L72 is doing)

**Comment by bitner** [comment]
There are two things going on here. 

1. We need to check what a user has permissions to see. This is all up to the database and cannot be overridden by anything that TiPG does - database privileges always trump. The calls to has_column_privilege, has_table_privilege, has_schema_privilege, and has_function_privilege make sure that we do not expose anything in the catalog  that the user connecting to the database should not be able to use.
2. We want to have some control to be able to filter over what is exposed by tipg regardless of permissions. Currently this is done partially on the database side to respect whatever is set in the search_path for the user that is connecting. This is where the pg_table_is_visible and pg_function_is_visible are kicking in. The exclude/include settings on TiPG are what kick in as additional filters when creating the catalog.

What this means is that if your schemas and function_schemas are set to NULL, then what shows up will be everything that is in the users search_path.

If the search_path is set to public, but schemas environment var is set to public,myschema only the tables from the public schema would show up. If the search_path for the user was set to public,myschema then tables from both would show up.

Looking through the code, I think that we could do a couple things that could make things a bit clearer.

1. Currently we default schemas and function_schemas to public. We should instead default those to NULL which would make the users search_path the default.
2. We should append all schemas listed in schemas/function_schemas environment variables to the search_path at the beginning of the connection.
