### ISSUE TITLE
Request: Pop-up in Leaflet

### ISSUE THREAD

**Issue by jonaraphael** [developmentseed/tipg#59]
It would be really helpful if clicking on any blue polygon item in the leaflet map displayed some pop-up text.

Ideally, that popup would show all the key:value pairs for that row (perhaps truncated if too long?).
At least, it should show the row # so that a user could scroll to that row and find the relevant data themselves.

Currently, the cursor turns into a pointing finger (which indicates a hyperlink), but nothing seems to happen when clicked.

**Comment by krishnaglodha** [comment]
Hi, I'd be happy to take up the task

**Comment by vincentsarago** [comment]
@krishnaglodha 🙌

**Comment by krishnaglodha** [comment]
Hi @vincentsarago , 
I've created .env file
```
TIPG_NAME="OGC Features and Tiles API - Krishna"
DATABASE_URL=postgresql://postgres:postgres@localhost:5432/postgres
```

1. I'm not able to see my layers in collection
2. and when I click on collection, I'm getting following error 
<img width="580" alt="Screenshot 2023-06-15 at 5 05 17 PM" src="https://github.com/developmentseed/tipg/assets/47075664/7f8fa7e1-2765-407c-a07c-3901adec785b">

**Comment by krishnaglodha** [comment]
Finally it is working on intel machine, I'm on it :)

**Comment by vincentsarago** [comment]
done in #91 🥳
