### ISSUE TITLE
`string_to_table` fails with Postgres < 14

### ISSUE THREAD

**Issue by yoninachmany** [developmentseed/tipg#67]
```
asyncpg.exceptions.UndefinedFunctionError: function string_to_table(text, unknown) does not exist
HINT:  No function matches the given name and argument types. You might need to add explicit type casts.
```

https://github.com/developmentseed/tipg/blob/main/tipg/sql/dbcatalog.sql#L131-L139

Result of running `uvicorn tipg.main:app`

**Comment by vincentsarago** [comment]
`string_to_table` was added in postgres 14 😓 (https://pgpedia.info/s/string_to_table.html)

cc @bitner
