### ISSUE TITLE
replace ciso8601  with speedate?

### ISSUE THREAD

**Issue by vincentsarago** [developmentseed/tipg#88]
https://github.com/developmentseed/tipg/blob/12a5e544259e32809f981b9d83f9b04eff6ba0d6/tipg/collections.py#L11C22-L11C35

https://github.com/pydantic/speedate

**Comment by krishnaglodha** [comment]
I can work on it

**Comment by vincentsarago** [comment]
that would be lovely @krishnaglodha 🙏

**Comment by krishnaglodha** [comment]
On it

Thank you,
Krishna G. Lodha
Personal email : ***@***.***
Office email : ***@***.***

**Comment by krishnaglodha** [comment]
Hi , speedate is rust package? am I missing some link ?

**Comment by vincentsarago** [comment]
@krishnaglodha 🤦 yes it is, I was assuming they published the python bindings but no 😓

**Comment by krishnaglodha** [comment]
@vincentsarago , let me know if you need me anywhere else . 
`GIS | PYTHON | DOCUMENTATION`
