### ISSUE TITLE
Pydantic 2 has some changes which break tipg

### ISSUE THREAD

**Issue by RemcoMeeuwissen** [developmentseed/tipg#90]
For now I've fixed it in our deployment by adding `pydantic == 1.10.11` in our requirements.txt, but if it breaks things for us I expect it will do so for others as well :sweat_smile:

**Comment by vincentsarago** [comment]
pydantic should be bounded by morecantile https://github.com/developmentseed/morecantile/blob/4.3.0/pyproject.toml#L25 so `pip` shouldn't install pydantic 2.0

**Comment by RemcoMeeuwissen** [comment]
Crap you're right, there was a pydantic[dotenv] requirement in there which caused the issue. Totally glanced over that, sorry!
